version: '3.8'

services:
  ticket-hub-visuals:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-hub-visuals-dev
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./components.json:/app/components.json
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - ticket-hub-network

networks:
  ticket-hub-network:
    driver: bridge
